name: Shell Commands

on: [push, pull_request]

jobs: 
  run-shell-command:
   runs-on: ubuntu-latest
   steps:
    - name: actualizar repositorio
      run: git clone https://github.com/jesusbrochado/aapc
    - name: test
      run: |
        ls -lh
        pwd
    - name: deploy
      working-directory: ./aapc
      run: |
        npm install
        npm build
        
    
